### ISSUE TITLE
Add REST style URLs on the generated actions

### ISSUE THREAD

**Issue by gil0mendes** [gil0mendes/stellar#6]
When the developer run the follow command `stellar makeModel comment --module=exampleModule --crud`, the Stellar will generate a model file and a set of actions. To make this more powerful we must add support to another options `--rest` to add REST like URLs on the actions declarations.

The follow text describe the format for the REST URLs:
```text
// get all resources
[GET] /resource

// get one resource 
[GET] /resource/:id

// create a resource
[POST] /resource

// edit a resource
[PUT] / resource/:id

// delete a resource
[DELETE] /resource/:id
```

**Comment by jaimetotal** [comment]
You say "REST-like URLs" but there are many flavors to it. Can you define a convention for it?

**Comment by gil0mendes** [comment]
Yap... I update the Issue description to specify the format for the REST URLs 😉
